apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhoim
  labels:
    app: rhoim
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rhoim
  labels:
    app: rhoim
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhoim
  labels:
    app: rhoim
subjects:
- kind: ServiceAccount
  name: rhoim
roleRef:
  kind: Role
  name: rhoim
  apiGroup: rbac.authorization.k8s.io
